config/routes.rb
Rails.application.routes.draw do


  post "likes/:product_id/create" => "likes#create"
  post "likes/:product_id/destroy" => "likes#destroy"


  resources :scenes
  resources :states
root "users#home"
  devise_for :admins
  resources :finalorders
  get "/faction" => "finalorders#finalaction"
  resources :carts

  get "/cupdate" => "carts#update"
  get "/cdelete" => "carts#destroy"

  # get 'carts/new'
  #
  # get 'carts/create'
  #
  # get 'carts/edit'
  #
  # get 'carts/update'
  #
  # get 'carts/index'
  #
  # get 'carts/show'
  #
  # get 'carts/destroy'

  resources :customers
  # get 'customers/new'
  #
  # get 'customers/edit'
  #
  # get 'customers/update'
  #
  # get 'customers/create'
  #
  # get 'customers/destroy'
  #
  # get 'customers/index'
  #
  # get 'customers/show'

  get '/login' => 'customers#login'
  post '/loginprocess' => 'customers#loginprocess'
  get '/logout' => 'customers#logout'

  resources :products
  # get 'products/new'
  #
  # get 'products/create'
  #
  # get 'products/edit'
  #
  # get 'products/update'
  #
  # get 'products/index'
  #
  # get 'products/show'
  #
  # get 'products/destroy'



  resources :categorys
  get 'hitem' => 'categorys#item'
  # get 'categorys/new' => "categorys#new"
  #
  # get 'categorys/edit'
  #
  # get 'categorys/create' => "categorys#create"
  #
  # get 'categorys/update'
  #
  # get 'categorys/destroy'
  #
  # get 'categorys/index'
  #
  # get 'categorys/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/users/home"
  get "/users/show"
  get "/users/:id", to: "users#decision_show"
  post "/users/:id", to: "users#decision_create"
  get "/users/introduce",to: "users#introduce"


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_secure_password
  mount_uploader :image, ImageUploader
  # 個々の記述大切です

  validates :name, {presence: true}
  validates :email, {presence: true}
  validates :dateofbirth, {presence: true}

  validates :address, {presence: true}

end

app/models/decision.rb
class Decision < ApplicationRecord
end

app/models/finalorder.rb
class Finalorder < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  validates :customer_id, {presence: true}
  validates :product_id, {presence: true}
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader


  validates :name, {presence: true}
  validates :price, {presence: true}
  validates :description, {presence: true}
  validates :image, {presence: true}
  validates :category_id, {presence: true}
  validates :state_id, {presence: true}
  validates :scene_id, {presence: true}

end


# これはgemを使ったときの話か

app/models/scene.rb
class Scene < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :set_scene, only: [:show, :edit, :update, :destroy]

  # GET /scenes
  # GET /scenes.json
  def index
    @scenes = Scene.all
  end

  # GET /scenes/1
  # GET /scenes/1.json
  def show
  end

  # GET /scenes/new
  def new
    @scene = Scene.new
  end

  # GET /scenes/1/edit
  def edit
  end

  # POST /scenes
  # POST /scenes.json
  def create
    @scene = Scene.new(scene_params)

    respond_to do |format|
      if @scene.save
        format.html { redirect_to @scene, notice: 'Scene was successfully created.' }
        format.json { render :show, status: :created, location: @scene }
      else
        format.html { render :new }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenes/1
  # PATCH/PUT /scenes/1.json
  def update
    respond_to do |format|
      if @scene.update(scene_params)
        format.html { redirect_to @scene, notice: 'Scene was successfully updated.' }
        format.json { render :show, status: :ok, location: @scene }
      else
        format.html { render :edit }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.json
  def destroy
    @scene.destroy
    respond_to do |format|
      format.html { redirect_to scenes_url, notice: 'Scene was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scene
      @scene = Scene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scene_params
      params.require(:scene).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finalorders_helper.rb
module FinalordersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/scenes/_form.html.erb
<%= form_with(model: scene, local: true) do |form| %>
  <% if scene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scene.errors.count, "error") %> prohibited this scene from being saved:</h2>

      <ul>
      <% scene.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :scene_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scenes/edit.html.erb
<h1>Editing Scene</h1>

<%= render 'form', scene: @scene %>

<%= link_to 'Show', @scene %> |
<%= link_to 'Back', scenes_path %>

app/views/scenes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scenes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scenes.each do |scene| %>
      <tr>
        <td><%= scene.name %></td>
        <td><%= link_to 'Show', scene %></td>
        <td><%= link_to 'Edit', edit_scene_path(scene) %></td>
        <td><%= link_to 'Destroy', scene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scene', new_scene_path %>

app/views/scenes/new.html.erb
<h1>New Scene</h1>

<%= render 'form', scene: @scene %>

<%= link_to 'Back', scenes_path %>

app/views/scenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scene.name %>
</p>

<%= link_to 'Edit', edit_scene_path(@scene) %> |
<%= link_to 'Back', scenes_path %>