config/routes.rb
Rails.application.routes.draw do


  post "likes/:product_id/create" => "likes#create"
  post "likes/:product_id/destroy" => "likes#destroy"


  resources :scenes
  resources :states
root "users#home"
  devise_for :admins
  resources :finalorders
  get "/faction" => "finalorders#finalaction"
  resources :carts

  get "/cupdate" => "carts#update"
  get "/cdelete" => "carts#destroy"

  # get 'carts/new'
  #
  # get 'carts/create'
  #
  # get 'carts/edit'
  #
  # get 'carts/update'
  #
  # get 'carts/index'
  #
  # get 'carts/show'
  #
  # get 'carts/destroy'

  resources :customers
  # get 'customers/new'
  #
  # get 'customers/edit'
  #
  # get 'customers/update'
  #
  # get 'customers/create'
  #
  # get 'customers/destroy'
  #
  # get 'customers/index'
  #
  # get 'customers/show'

  get '/login' => 'customers#login'
  post '/loginprocess' => 'customers#loginprocess'
  get '/logout' => 'customers#logout'

  resources :products
  # get 'products/new'
  #
  # get 'products/create'
  #
  # get 'products/edit'
  #
  # get 'products/update'
  #
  # get 'products/index'
  #
  # get 'products/show'
  #
  # get 'products/destroy'



  resources :categorys
  get 'hitem' => 'categorys#item'
  # get 'categorys/new' => "categorys#new"
  #
  # get 'categorys/edit'
  #
  # get 'categorys/create' => "categorys#create"
  #
  # get 'categorys/update'
  #
  # get 'categorys/destroy'
  #
  # get 'categorys/index'
  #
  # get 'categorys/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/users/home"
  get "/users/show"
  get "/users/:id", to: "users#decision_show"
  post "/users/:id", to: "users#decision_create"
  get "/users/introduce",to: "users#introduce"


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_secure_password
  mount_uploader :image, ImageUploader
  # 個々の記述大切です

  validates :name, {presence: true}
  validates :email, {presence: true}
  validates :dateofbirth, {presence: true}

  validates :address, {presence: true}

end

app/models/decision.rb
class Decision < ApplicationRecord
end

app/models/finalorder.rb
class Finalorder < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  validates :customer_id, {presence: true}
  validates :product_id, {presence: true}
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader


  validates :name, {presence: true}
  validates :price, {presence: true}
  validates :description, {presence: true}
  validates :image, {presence: true}
  validates :category_id, {presence: true}
  validates :state_id, {presence: true}
  validates :scene_id, {presence: true}

end


# これはgemを使ったときの話か

app/models/scene.rb
class Scene < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/finalorders_controller.rb
class FinalordersController < ApplicationController
  before_action :set_finalorder, only: [:show, :edit, :update, :destroy]

  # GET /finalorders
  # GET /finalorders.json
  def index
    @finalorders = Finalorder.all
  end

  # GET /finalorders/1
  # GET /finalorders/1.json
  def show
    @cart = Cart.where(userid: session[:myid])
    @customer = Customer.find_by(id: params[:recipient_id])
    # binding.pry

  end

  # GET /finalorders/new
  def new
    @finalorder = Finalorder.new
    @customer = Customer.find_by(id: session[:myid])
    @cart = Cart.where(userid: session[:myid])
    @opponent_user = Customer.all

  end

  # GET /finalorders/1/edit
  def edit
  end

  # POST /finalorders
  # POST /finalorders.json
  def create
    @finalorder = Finalorder.new(finalorder_params)

    respond_to do |format|
      if @finalorder.save
        format.html { redirect_to @finalorder, notice: 'Finalorder was successfully created.' }
        format.json { render :show, status: :created, location: @finalorder }
      else
        format.html { render :new }
        format.json { render json: @finalorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finalorders/1
  # PATCH/PUT /finalorders/1.json
  def update
    respond_to do |format|
      if @finalorder.update(finalorder_params)
        format.html { redirect_to @finalorder, notice: 'Finalorder was successfully updated.' }
        format.json { render :show, status: :ok, location: @finalorder }
      else
        format.html { render :edit }
        format.json { render json: @finalorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finalorders/1
  # DELETE /finalorders/1.json
  def destroy
    @finalorder.destroy
    respond_to do |format|
      format.html { redirect_to finalorders_url, notice: 'Finalorder was successfully destroyed.' }
      format.json { head :no_content }
      @cart = Cart.where(userid: session[:myid])
      @cart.destroy
      respond_to faction
    end
  end

  def finalaction
    @cart = Cart.where(userid: session[:myid]).destroy_all

    @youbi = %w[(日) (月) (火) (水) (木) (金) (土)]
    d = Date.today
    @deliverday = d + 14

    # 送り先のユーザーを取ってくる処理
    # order_descのインスタンスを一回作らないと値がうまく取ってこれなかった
    order_desc = Finalorder.order("created_at DESC")
    @finalorder = order_desc.find_by(user_id: session[:myid])
    @recipient = Customer.find_by(id: @finalorder.recipient_id)

    # binding.pry
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finalorder
      @finalorder = Finalorder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finalorder_params
      params.require(:finalorder).permit(:username, :phonenumber, :address, :email, :delivery, :payment, :gift, :user_id, :product_id, :quantity, :recipient_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finalorders_helper.rb
module FinalordersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/finalorders/_form.html.erb
<div class="f-container-1">

  <%
        @proid="";
        @quan="";
          @cart.each do |fff|
            @proid += [fff.product_id].join('')+","
            @quan += [fff.number].join('')+","
          end
# ココめっちゃ大事proid="";quan="";をstringで宣言してその中に@cartの中身をeachで回す。.join('')でfff.product_id]をstringにしてまとめる

   %>
  <%= @proid.chop %> <br>
  <%= @quan.chop %> <br>


  <%= form_with(model: finalorder, local: true) do |form| %>
    <% if finalorder.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(finalorder.errors.count, "error") %> prohibited this finalorder from being saved:</h2>

        <ul>
        <% finalorder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>



    <div class="field">
      <!-- <%= form.label :username %> <br> -->
      自分 <br>
      <%= form.text_field :username, value: @customer.name%>
    </div>

    <div class="field">
      <!-- <%= form.label :username %> <br> -->
      送り相手 <br>
      <%= form.select :recipient_id, options_from_collection_for_select(Customer.all, :id, :name), :include_blank => "送り相手を選択する" %>
    </div>


    <!-- <div class="field">
      電話番号<br>
      <%= form.number_field :phonenumber, id: :phonenumber %>
    </div>

    <div class="field">
      住所<br>
      <%= form.text_field :address, id: :finalorder_address %>
    </div>

    <div class="field">
      メールアドレス<br>
      <%= form.text_field :email, value: @customer.email%>
    </div>

    <input type="button" name="" value="Next" class="btn btn-success fbtn1">
  </div>


  <div class="f-container-2">
    <div class="field">
      <%= form.label :delivery %><br>
      <%= form.radio_button :delivery,"home", :checked => true %>Home
      <%= form.radio_button :delivery, 'office' %>Office
      <%= form.radio_button :delivery, 'conviniencestore' %>Convinience Store
    </div>

    <div class="field">
      <%= form.label :payment %><br>
      <%= form.radio_button :payment,"card", :checked => true %>Card
      <%= form.radio_button :payment,"cash"%>Cash on Delevery
      <%= form.radio_button :payment,"bank"%>Bank transfer
      <%= form.radio_button :payment,"convini"%>Convinience Store
    </div>

    <input type="button" name="" value="Next" class="btn btn-success fbtn2">
    <a class="fbtn-back1">Back</a>
  </div>

  <div class="f-container-3">
      <div class="field">
        <%= form.label :gift %><br>
        <%= form.radio_button :gift, "wrap"%>Gift wrapping
        <%= form.radio_button :gift, "no", :checked => true %>No wrapping
      </div> -->
      <!-- 一旦消す -->


      <%= form.hidden_field :user_id, value: session[:myid]%>
      <%= form.hidden_field :product_id, value: @proid.chop %>
      <%= form.hidden_field :quantity, value: @quan.chop%>
         
      <div class="actions">
        <%= form.submit class: "btn btn-success"%>
      </div>

      <a class="fbtn-back2">Back</a>
    <% end %>
  </div>

app/views/finalorders/edit.html.erb
<h1>Editing Finalorder</h1>

<%= render 'form', finalorder: @finalorder %>

<%= link_to 'Show', @finalorder %> |
<%= link_to 'Back', finalorders_path %>

app/views/finalorders/finalaction.html.erb
<div class="row">
  <div class="col-md-offset-2">

    <h2>ご利用ありがとうございます！<br>
    <span style="color:red;"> <%= @recipient.name %> </span>さんにお送りになられたカタログギフトは<span style="color:red;"> <%= @recipient.name %> </span>さんのアカウントに送信されました。 <br>
    <span style="color:red;"> <%= @recipient.name %> </span>さんの回答期限は <%= @deliverday %> <%= @youbi[@deliverday.wday] %>としております。</h2>
    <%= fa_icon "ambulance 4x horizonta"%>



    <%= link_to "ホーム画面へ戻る", users_home_path %>
  </div>
</div>

app/views/finalorders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Finalorders</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Phonenumber</th>
      <th>Address</th>
      <th>Email</th>
      <th>Delivery</th>
      <th>Payment</th>
      <th>Gift</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finalorders.each do |finalorder| %>
      <tr>
        <td><%= finalorder.username %></td>
        <td><%= finalorder.phonenumber %></td>
        <td><%= finalorder.address %></td>
        <td><%= finalorder.email %></td>
        <td><%= finalorder.delivery %></td>
        <td><%= finalorder.payment %></td>
        <td><%= finalorder.gift %></td>
        <td><%= link_to 'Show', finalorder %></td>
        <td><%= link_to 'Edit', edit_finalorder_path(finalorder) %></td>
        <td><%= link_to 'Destroy', finalorder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Finalorder', new_finalorder_path %>

app/views/finalorders/new.html.erb
<div class="row">


<div class="col-md-offset-2 col-md-4">

  <i class="fas fa-accessible-icon"></i>
  <i class="fab fa-accessible-icon"></i>
  <%= fa_icon "twitter" %>
  <%= fa_icon "ambulance 5x horizonta" %>
<h1>カタログ送信先</h1>

<%= render 'form', finalorder: @finalorder %>

<!-- <%= link_to 'Back', finalorders_path %> -->
</div>

<div class="col-md-offset-4">
  <h2>あなたがカスタマイズしたカタログ</h2>
  <table class="table" style="width:500px">
      <thead>
        <tr>
          <th></th>
          <th>アイテム</th>
          <th>値段</th>
          <th>個数</th>
        </tr>
      </thead>

      <%
      pr = 0;
      @cart.each do |cart|
      @productone = Product.find_by(id: cart.product_id)
      pr = pr + cart.subtotal
      # ココどうやって書こうか
      %>

      <tbody>
        <tr>
          <td> <%= image_tag(@productone.image, :width => "50px", :height => "50px") %> </td>
          <td> <%= @productone.name %></td>
          <td> ¥<%= cart.productprice %> </td>
          <td> <%= cart.number %> </td>
        </tr>
      </tbody>
      <% end %>
      <thead>
        <tr style="font-size:20px">
          <th></th>
          <th></th>
          <th>合計( <%= @cart.count %> 個)</th>
          <th style="color:rgb(231, 137, 51)">:¥ <%= pr %> </th>
        </tr>
      </thead>
    </table>

</div>
</div>

app/views/finalorders/show.html.erb
<div class="col-md-offset-2">
<h2>カタログリスト（確認）</h2>
  <table class="table" style="width:500px">
      <thead>
        <tr>
          <th></th>
          <th>商品</th>
          <th>値段</th>
          <th>個数</th>
        </tr>
      </thead>

      <%
      pr = 0;
      @cart.each do |cart|
      @productone = Product.find_by(id: cart.product_id)
      pr = pr + cart.subtotal
      # ココどうやって書こうか
      %>

      <tbody>
        <tr>
          <td> <%= image_tag(@productone.image, :width => "50px", :height => "50px") %> </td>
          <td> <%= @productone.name %></td>
          <td> ¥<%= cart.productprice %> </td>
          <td> <%= cart.number %> </td>
        </tr>
      </tbody>
      <% end %>
      <thead>
        <tr style="font-size:20px">
          <th></th>
          <th></th>
          <th>合計( <%= @cart.count %> items)</th>
          <th style="color:rgb(231, 137, 51)">:¥<%= pr %> </th>
        </tr>
      </thead>
    </table>


<p id="notice"><%= notice %></p>

<p>
  <strong>送り元:</strong><br>
  <%= @finalorder.username %>
</p>
<p>
  <strong>送り先:</strong><br>
  <% @recipient = Customer.find_by(id: @finalorder.recipient_id) %>
  <%= @recipient.name %>
  <!-- <%= @finalorder.recipient_id %> -->

</p>

<!-- <p>
  <strong>Phone Number:</strong><br>
  <%= @finalorder.phonenumber %>
</p>

<p>
  <strong>Address:</strong><br>
  <%= @finalorder.address %>
</p> -->

<p>
  <strong>Mail Address:</strong><br>
  <%= @finalorder.email %>
</p>

<!-- <p>
  <strong>Delivery:</strong><br>
  <%= @finalorder.delivery %>
</p>

<p>
  <strong>Payment:</strong><br>
  <%= @finalorder.payment %>
</p> -->

<!-- <p>
  <strong>Gift:</strong><br>
  <%= @finalorder.gift %>
</p> -->
<%= link_to faction_path do %>
<button type="button" class="btn btn-success" style="margin-top:30px;">カタログを送る</button>
<% end %>
<%= link_to 'Edit', edit_finalorder_path(@finalorder) %> |
<%= link_to 'Back', finalorders_path %>

</div>