config/routes.rb
Rails.application.routes.draw do


  post "likes/:product_id/create" => "likes#create"
  post "likes/:product_id/destroy" => "likes#destroy"


  resources :scenes
  resources :states
root "users#home"
  devise_for :admins
  resources :finalorders
  get "/faction" => "finalorders#finalaction"
  resources :carts

  get "/cupdate" => "carts#update"
  get "/cdelete" => "carts#destroy"

  # get 'carts/new'
  #
  # get 'carts/create'
  #
  # get 'carts/edit'
  #
  # get 'carts/update'
  #
  # get 'carts/index'
  #
  # get 'carts/show'
  #
  # get 'carts/destroy'

  resources :customers
  # get 'customers/new'
  #
  # get 'customers/edit'
  #
  # get 'customers/update'
  #
  # get 'customers/create'
  #
  # get 'customers/destroy'
  #
  # get 'customers/index'
  #
  # get 'customers/show'

  get '/login' => 'customers#login'
  post '/loginprocess' => 'customers#loginprocess'
  get '/logout' => 'customers#logout'

  resources :products
  # get 'products/new'
  #
  # get 'products/create'
  #
  # get 'products/edit'
  #
  # get 'products/update'
  #
  # get 'products/index'
  #
  # get 'products/show'
  #
  # get 'products/destroy'



  resources :categorys
  get 'hitem' => 'categorys#item'
  # get 'categorys/new' => "categorys#new"
  #
  # get 'categorys/edit'
  #
  # get 'categorys/create' => "categorys#create"
  #
  # get 'categorys/update'
  #
  # get 'categorys/destroy'
  #
  # get 'categorys/index'
  #
  # get 'categorys/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/users/home"
  get "/users/show"
  get "/users/:id", to: "users#decision_show"
  post "/users/:id", to: "users#decision_create"
  get "/users/introduce",to: "users#introduce"


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_secure_password
  mount_uploader :image, ImageUploader
  # 個々の記述大切です

  validates :name, {presence: true}
  validates :email, {presence: true}
  validates :dateofbirth, {presence: true}

  validates :address, {presence: true}

end

app/models/decision.rb
class Decision < ApplicationRecord
end

app/models/finalorder.rb
class Finalorder < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  validates :customer_id, {presence: true}
  validates :product_id, {presence: true}
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader


  validates :name, {presence: true}
  validates :price, {presence: true}
  validates :description, {presence: true}
  validates :image, {presence: true}
  validates :category_id, {presence: true}
  validates :state_id, {presence: true}
  validates :scene_id, {presence: true}

end


# これはgemを使ったときの話か

app/models/scene.rb
class Scene < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  respond_to :js, :html ,:json
  def new

  end

  def create
    if session[:myid]
      @c = Cart.new(cart_params)
      @c.save
      @cart = Cart.where(userid: session[:myid]).last
      @productone = Product.find_by(id: @cart.product_id)
      @productsub = Product.all
      # ココ復習しなさい！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
    else
      redirect_to login_path
    end


  end

  def edit

  end

  def update
    @cart = Cart.find(params[:cart][:id])
    @cart = @cart.update(number: params[:cart][:quan], subtotal: params[:cart][:subto])
    respond_to do |format|
      format.html
      format.json{render :json => { "mess": "success" }}
      # こんな書き方もできるよ
    end
    # @cart = Cart.update(cart_params)
    # sonu wrote
  end

  def index
    if session[:myid]
      @cart = Cart.where(userid: session[:myid])
      # viewファイるの中に書いた
      @productsub = Product.all
      respond_to do |format|
        format.html
        format.json{render :json => @cart}
        # ↑の@cartはajaxにデータを送るためのもの
      end

    else
      redirect_to login_path
    end

  end

  def show
  end

  def destroy
    @cart = Cart.find(params[:cart][:id])
    @cart.destroy
    respond_to do |format|
      format.html
      format.json{render :json => { "message": "delete success" }}
    end
  end

  def cart_params
    params.require(:cart).permit(:userid, :productprice, :productname, :subtotal, :number, :product_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finalorders_helper.rb
module FinalordersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/create.html.erb
<div class="whole container-fluid">
  <div class="row" style="border: 1px solid rgb(216, 213, 217)">
    <div class="col-md-1" style="margin-top:30px; padding-left:30px; font-size:30px">
      ✔
    </div>
    <div class="col-md-1">
      <!-- 謎にエラーがでる -->
      <!-- <%= @productone.id %> -->
      <%= image_tag(@productone.image, :width => "100px", style: "margin-left:-20px;") %>
      <!-- 画像を別テーブルから取ってくる -->
      <!-- ココ重要！！！ -->
    </div>
    <div class="col-md-1" style="font-size:14px; line-height:16px; margin-top:20px;">
      <b><%= @productone.name %> <br>
      Added to Cart</b>
    </div>
    <div class="col-md-5 " style="font-size:20px; margin-top:5px; ">
      Item Quantity: <%= @cart.number %> <br>
      Price: Rs. <%= @productone.price %> <br>
      Cart subtotal:Rs. <%= @cart.subtotal %>
    </div>
    <div class="col-md-4" style="margin-top:30px;">
      <%= link_to carts_path do %>
        <button href = "/users/new" type="button" class="btn btn-warning">cart</button>
      <% end %>
      <!-- ファイナルオーダーのNEWに飛ばす -->
      <%= link_to new_finalorder_path do %>
        <button type="button" class="btn btn-success">Proceed to Checkout</button>
      <% end %>

    </div>
  </div>

  <div class="row" style="margin-top:30px; border-radius:1%; border: 1px solid rgb(216, 213, 217);background-color:rgb(246, 246, 246)">
    <div class="" style="font-size:25px;">
      Check Other Items
    </div>

    <div id="css-slider">
     <div class="slider-wrapper">
      <% @productsub.each do |p| %>
          <div class="col-md-3 goodscol slide-item">
            <%= link_to image_tag(p.image, :width => "240px", :height => "240px"), product_path(p.id) %><br>
            <span class="categorydevide"><%= p.name %></span> <br>
            Rs. <%= p.price %>

             <div id="kinds"> # <%= p.category_id %> </div>
          </div>
       <% end %>
      </div>
    </div>
  </div>
</div>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<script>
 $(document).ready(function(){

 });
</script>

<div class="whole container-fluid">
<%
pr = 0;
@cart.each do |cart|
@productone = Product.find_by(id: cart.product_id)
pr = pr + cart.subtotal
# 総額を出すときの変数pr
%>
<!-- このページはまじで意味わからんとくにID -->
<!-- 見直そう -->
<!-- データベースの中にNULLが入っていてバグが出ていた。 -->
  <div class="row" id="cartbox-<%= cart.id %>" style="border: 1px solid rgb(216, 213, 217)">
    <div class="col-md-1" style="margin-top:30px; padding-left:30px; font-size:30px">
      ✔
    </div>
    <div class="col-md-1">

      <%= image_tag(@productone.image, :width => "100px", :height => "100px", style: "margin-left:-20px;") %>

    </div>
    <div class="col-md-1" style="font-size:14px; line-height:16px; margin-top:20px;">
      <span id="pname-<%= cart.id %>"> <%= @productone.name %></span>  <br>
      カートに入っています</b>
    </div>
    <div class="col-md-5 " style="font-size:20px; margin-top:5px; ">
      個数: <span class="quan" id="q-<%= cart.id %>"> <%= cart.number %></span> <br>
      <!-- Price: Rs. <span class="price" id="p-<%= cart.id %>"> <%= cart.productprice %> </span><br> -->
      <!-- Price: Rs. <span class="price" id="p-<%= cart.id %>"> <%= @productone.price %> </span><br> -->
      小計:¥<span class="subtotaleach" id="sub-<%= cart.id %>"> <%= cart.subtotal %></span>
    </div>

    <script>
      var cartNumber = <%= cart.number %>;
      var cartPrice = <%= @productone.price %>;
      // いらない↑
    </script>

    <div class="col-md-4" style="margin-top:30px;">
      <select class="gnum_cart" name="" data="<%= cart.id %>" >
        <!-- ココのdataをjqueryのdataにぶち込む -->
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
      </select>
      <!-- <%= link_to carts_path do %> -->
      <!-- AJAXを使うときにはRUBYタグで囲まない -->
        <button data="<%= cart.id %>" type="button" class="btn btn-warning subtotalbutton ">変更</button>
      <!-- <% end %> -->
      <!-- ファイナルオーダーのNEWに飛ばす -->
      <!-- <%= link_to new_finalorder_path do %> -->
        <button data="<%= cart.id %>" type="button" class="btn btn-success deletebutton">削除</button>
      <!-- <% end %> -->

    </div>
  </div>
<% end %>

<div class=" row bg-success" >
  <span style="float:right; font-size:20px;"> 合計金額( <%= @cart.count %>商品 ):¥<%= pr %> </span><br>
  <%= link_to new_finalorder_path do %>
    <button type="button" class="btn btn-success" style="float:right; margin-top:30px;">送り先を選ぶ</button>

</div>
<% end %>

  <div class="row" style="margin-top:30px; border-radius:1%; border: 1px solid rgb(216, 213, 217);background-color:rgb(246, 246, 246)">
    <div class="" style="font-size:25px;">
      あなたへのオススメ
    </div>

    <div id="css-slider">
     <div class="slider-wrapper">
      <% @productsub.each do |p| %>
          <div class="col-md-3 goodscol slide-item">
            <%= link_to image_tag(p.image, :width => "240px", :height => "240px"), product_path(p.id) %><br>
            <span class="categorydevide"><%= p.name %></span> <br>
            ¥<%= p.price %>

             <div id="kinds"> # <%= p.category_id %> </div>
          </div>
       <% end %>
      </div>
    </div>
  </div>
</div>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>