config/routes.rb
Rails.application.routes.draw do


  post "likes/:product_id/create" => "likes#create"
  post "likes/:product_id/destroy" => "likes#destroy"


  resources :scenes
  resources :states
root "users#home"
  devise_for :admins
  resources :finalorders
  get "/faction" => "finalorders#finalaction"
  resources :carts

  get "/cupdate" => "carts#update"
  get "/cdelete" => "carts#destroy"

  # get 'carts/new'
  #
  # get 'carts/create'
  #
  # get 'carts/edit'
  #
  # get 'carts/update'
  #
  # get 'carts/index'
  #
  # get 'carts/show'
  #
  # get 'carts/destroy'

  resources :customers
  # get 'customers/new'
  #
  # get 'customers/edit'
  #
  # get 'customers/update'
  #
  # get 'customers/create'
  #
  # get 'customers/destroy'
  #
  # get 'customers/index'
  #
  # get 'customers/show'

  get '/login' => 'customers#login'
  post '/loginprocess' => 'customers#loginprocess'
  get '/logout' => 'customers#logout'

  resources :products
  # get 'products/new'
  #
  # get 'products/create'
  #
  # get 'products/edit'
  #
  # get 'products/update'
  #
  # get 'products/index'
  #
  # get 'products/show'
  #
  # get 'products/destroy'



  resources :categorys
  get 'hitem' => 'categorys#item'
  # get 'categorys/new' => "categorys#new"
  #
  # get 'categorys/edit'
  #
  # get 'categorys/create' => "categorys#create"
  #
  # get 'categorys/update'
  #
  # get 'categorys/destroy'
  #
  # get 'categorys/index'
  #
  # get 'categorys/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/users/home"
  get "/users/show"
  get "/users/:id", to: "users#decision_show"
  post "/users/:id", to: "users#decision_create"
  get "/users/introduce",to: "users#introduce"


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_secure_password
  mount_uploader :image, ImageUploader
  # 個々の記述大切です

  validates :name, {presence: true}
  validates :email, {presence: true}
  validates :dateofbirth, {presence: true}

  validates :address, {presence: true}

end

app/models/decision.rb
class Decision < ApplicationRecord
end

app/models/finalorder.rb
class Finalorder < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  validates :customer_id, {presence: true}
  validates :product_id, {presence: true}
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader


  validates :name, {presence: true}
  validates :price, {presence: true}
  validates :description, {presence: true}
  validates :image, {presence: true}
  validates :category_id, {presence: true}
  validates :state_id, {presence: true}
  validates :scene_id, {presence: true}

end


# これはgemを使ったときの話か

app/models/scene.rb
class Scene < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_header.html.erb
<a class="navbar-brand" > <%= image_tag("ecsite_pic/ateamlogo.png", :style => "width:400px; margin-left: 30px;") %> </a>


<div class="hbutton1" style="padding-top:10px;">




  <%= link_to users_home_path do %>
    <button class ="hbutton btn btn-outline-info" type="button" >
      <%= fa_icon("home", text: "Home")%>
    </button>
  <% end %>
  <!-- 埋め込みフォントオウサム対応 -->


<!-- <div class="dropdown" style="padding-left:70px;"> いらなかった？6/27-->
    <button class ="hbutton btn btn-outline-info itembutton dropdown-toggle" type="button" data-toggle="dropdown">
      <%= fa_icon("book", text: "Category" )%>
    </button>
  <div class="dropdown-menu" style="margin-left:1000px">
    <% Category.all.each do |c| %>
    <!-- ローカル変数で定義したかったけど、Category.allでとってこれてしまった。 -->
      <span class="tab2">  <button type="button" name="button" class="categoryb2" value="<%= c.name %> "><%= c.name %></button> </span> <br>
    <% end %>
  </div>


  <% if session[:myid] %>
    <%= link_to logout_path do %>
      <!-- <input class =" btn btn-danger" type="button" name="" value="LOGOUT"> -->
      <button class ="hbutton btn btn-outline-info" type="button" name="" value="LOGOUT">
        <%= fa_icon("sign-out", text: "Logout")%>
      </button>
    <% end %>
  <% else %>
    <%= link_to login_path do %>
      <button class ="hbutton btn btn-outline-info" type="button" name="" value="LOGIN">
        <%= fa_icon("sign-in", text: "Login")%>
      </button>
    <% end %>

    <%= link_to new_customer_path do %>
      <button class ="hbutton btn btn-outline-info" type="button" name="" value="REGISTAR">
        <%= fa_icon("registered", text: "Register")%>
      </button>
    <% end %>
  <% end %>



  <%= link_to carts_path do %>
    <button class ="hbutton btn btn-outline-info" type="button" name="" value="CART" style="height: 44px">
      <%= fa_icon("cart-plus", text: "Cart")%>
    </button>
  <% end %>

  <% unless session[:myimage].blank? %>
  <%= link_to users_show_path do %>
  <button class ="hbutton btn btn-outline-info" type="button">
    <span> <%= image_tag(session[:myimage], width: "29px", style: "border-radius:100%; margin: 0px;") %> </span>
    <span> <%= session[:myname] %>  </span>
    <span> <%= session[:myage] %> </span>
    <span> <%= session[:mygender] %> </span>
  </button>
  <% end %>
  <% end %>




  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aturae</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'ateam.png'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!-- <link rel="stylesheet" href="bootstrap/dist/css/bootstrap.css"> -->
    <!-- <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script> -->
    <!-- フォントオウサムのインストール -->
  </head>

  <body>
    <!-- <div class="whole container-fluid"> -->
    <div class="" id="fixed">

    <%= render "layouts/header", categories: @categories %>

<!-- ↑だめだった いけた -->
<!-- partial必要？ -->
<% if flash[:notice]%>
  <div class="flash">
    <%= flash[:notice]%>
  </div>
<% end %>
    </div>




<div style="margin-top:150px">
  <!-- fixed-topに合わせるための余白 -->
  <%= yield %>

</div>
    <div class="bottom">
      <p class="bword">Ateam team E. All Rights Reserved.</p>
    </div>

    <!-- <button class="samplebuttom"type="button" name="button">aaaaaaaaaaas</button>
    <div class="samplebuttom">
      <h1>aaaaaa</h1>
    </div> -->

  </body>
</html>